import { twMerge } from "tailwind-merge";

export const SharedStyles = {
  button: twMerge(
    "bg-white",
    "w-fit",
    "text-center",
    "py-3 px-5",
    "rounded-3xl",
    "font-light",
    "tracking-wide",
    "border border-white",
    "hover:not-disabled:bg-dark-turquoise",
    "hover:not-disabled:text-white",
    "hover:not-disabled:font-normal",
  ),
  section: "px-16 py-12 pb-20",
  sectionHeader: "text-6xl mb-12",
  subHeader: "text-2xl/loose",
  logisticsItem: "mb-8",
  itemHeader: "text-xl/loose font-light",
  paragraph: "text-base/loose font-light text-justify",
  buttonAlt: "block size-max bg-black text-white px-12 py-6 rounded-full font-bold",
  card: twMerge(
    "flex",
    "bg-white",
    "w-[20%]",
    "rounded-custom",
    "min-w-[200px]",
    "md:min-w-[250px]",
    "h-[325px]",
    "md:h-[400px]",
    "hover:shadow-lg",
    "transition-all",
    "duration-300",
    "ease-in-out"
  ),
  cardHeader: "font-bold md:text-2xl text-xl",
  cardBody: "w-[80%] text-center md:mt-5 md:text-sm text-xs my-3",
  link: "flex flex-col items-center justify-center",
  img: "md:pb-6 w-[150px] h-auto pb-3",
};
